version: "3.8"

services:
  web:
    image: php:8.0-apache
    container_name: sp-conduite-accompagnee
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: bdd-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sp-conduite-accompagnee-bdd
      MYSQL_USER: julie.lausecker
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8086:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
